### ISSUE TITLE
Implement Relaton for Project PLATEAU

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-plateau#3]
You can now fetch them with:

```ruby
require_relative "../lib/relaton/plateau"

Relaton::Plateau::Fetcher.fetch_handbooks
Relaton::Plateau::Fetcher.fetch_technical_reports
```

The `Bibitem` class is where you want to replace it with Relaton.

**Comment by andrew2net** [comment]
@ronaldtse can't find how to map `cover`, `filesize`, and `tags` to our model. Possible `tags` are `keyword`, right? But for others I don't see anything appropriate.

**Comment by ronaldtse** [comment]
Let's extend our model to contain cover page images, file size, and keywords (tags). 

Metanorma already provides keywords for some standards.

**Comment by andrew2net** [comment]
@ronaldtse handbooks dataset has versions, so with ID like `"PLATEAU Handbook ##{entry["slug"]}"` we get duplications. We can parse version number from version title `"第4.0版"` and add it to ID `"PLATEAU Handbook ##{entry["slug"]}-#{ver}"`. Is it ok?

**Comment by ronaldtse** [comment]
@andrew2net yes we should use these patterns:

* Handbook: `PLATEAU Handbook #01 第4.0版`
* Technical Report: `PLATEAU Technical Report #93`

**Comment by andrew2net** [comment]
@ronaldtse there are handbooks with the same number and version but a different purpose of use. Is it ok if we have IDs like these?
- `PLATEAU Handbook #11 第1.0版（民間活用編)` - private sector use
- `PLATEAU Handbook #11 第1.0版（公共活用編)` - public use

And, there are handbooks with the number 09 and titles like "第1.0版 実証環境構築マニュアル". So when an ID is created with the title it looks like:

`PLATEAU Handbook #09 第1.0版 実証環境構築マニュアル`

Should we remove the "実証環境構築マニュアル" from IDs?

**Comment by ronaldtse** [comment]
> @ronaldtse there are handbooks with the same number and version but a different purpose of use. Is it ok if we have IDs like these?
> 
> * `PLATEAU Handbook #11 第1.0版（民間活用編)` - private sector use
> * `PLATEAU Handbook #11 第1.0版（公共活用編)` - public use

Yes, this is how we should do it.

> And, there are handbooks with the number 09 and titles like "第1.0版 実証環境構築マニュアル". So when an ID is created with the title it looks like:
> 
> `PLATEAU Handbook #09 第1.0版 実証環境構築マニュアル`
> 
> Should we remove the "実証環境構築マニュアル" from IDs?

Let me open a new issue for this.

**Comment by andrew2net** [comment]
this gem is released

**Comment by ronaldtse** [comment]
@andrew2net thanks! Please help update relaton.org to show how to cite PLATEAU documents. Thanks.
