### ISSUE TITLE
Handling Handbook #09 with different edition names

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-plateau#5]
From @andrew2net:

there are handbooks with the number 09 and titles like "第1.0版 実証環境構築マニュアル". So when an ID is created with the title it looks like:

`PLATEAU Handbook #09 第1.0版 実証環境構築マニュアル`

_Originally posted by @ronaldtse in https://github.com/relaton/relaton-plateau/issues/3#issuecomment-2244045846_

**Comment by ronaldtse** [comment]
I did some investigation and actually the title of Handbook 09 changed from Edition 1-3 to Edition 4.

|Edition 1 to 3 the title was: "実証環境構築マニュアル" | Edition 4 the title was: "PLATEAU VIEW構築マニュアル"|
|--|--|
|<img width="628" alt="image" src="https://github.com/user-attachments/assets/25044193-9c2f-42b0-bbfe-37d5b482afe8"> | <img width="628" alt="Screenshot 2024-07-23 at 8 44 21 AM" src="https://github.com/user-attachments/assets/6fb34022-c024-438b-a62c-a999ae19e72b"> |

They also mention the title change in the change history section:
<img width="1086" alt="Screenshot 2024-07-23 at 8 44 00 AM" src="https://github.com/user-attachments/assets/5b12d9d4-8f86-49f9-af5a-2c00a487754f">

The technically correct way to handle this is to have different titles for the handbook editions, and link them together through relations.

So the PubIDs of the editions should just be:
```
PLATEAU Handbook #09 第1.0版
PLATEAU Handbook #09 第2.0版
PLATEAU Handbook #09 第3.0版
PLATEAU Handbook #09 第4.0版
```

**Comment by ronaldtse** [comment]
This also means we need to do a PubID effort for PLATEAU.

@mico can you please do one quick? Thanks.

**Comment by andrew2net** [comment]
implemented
