### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-plateau#8]

**Comment by andrew2net** [comment]
@ronaldtse Did I miss something in the README?

**Comment by ronaldtse** [comment]
Yes please help update it:

> You can use it to retrieve metadata of ISO Standards from https://www.iso.org/, and access such metadata through the IsoBibliographicItem object.

**Comment by andrew2net** [comment]
Updated

**Comment by ronaldtse** [comment]
@andrew2net if you put in the commit message “fixes #8”, then when the commit lands in the main branch, the issue will automatically close itself.
