### ISSUE TITLE
uninitialized constant Relaton::Index::FileIO::Pubid

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-plateau#9]
Getting this error when I try to run relaton-plateau queries, and when I run rspec on relaton-plateau

````
     RelatonBib::RequestError:
       uninitialized constant Relaton::Index::FileIO::Pubid
     # ./lib/relaton/plateau/bibliography.rb:23:in `rescue in get'
     # ./lib/relaton/plateau/bibliography.rb:13:in `get'
     # ./spec/relaton/plateau/bibliography_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NameError:
     #   uninitialized constant Relaton::Index::FileIO::Pubid
     #   ./lib/relaton/plateau/bibliography.rb:27:in `search'
````

This is triggered by:

````
def index
        Relaton::Index.find_or_create :plateau, url: "#{GHURL}#{INDEXFILE}.zip", file: "#{INDEXFILE}.yaml"
end

def search(code)
        rows = index.search { |r| r[:id] ==  code }
...
````

**Comment by opoudjis** [comment]
Related: all my spec files have versions of:

````
allow_any_instance_of(Relaton::Index::Type).to receive(:actual?)
          .and_return(false)
````

With the update to relaton-index, this is now giving:

````
      NameError:
        uninitialized constant Relaton::Index
      # ./spec/metanorma/refs_spec.rb:5:in `block (2 levels) in <top (required)>'
````

Please advise on what I should update that to, so I don't get the issue I had been getting with failing to read in VCRs.

**Comment by andrew2net** [comment]
New version of relaton-index was released without testing with relaton-* gems. The wrong release was yanked. Please downgrade your local relaton-index instance to v0.2.12

**Comment by opoudjis** [comment]
bundle install is still fetching the newer gem, and that needs to be resolved before Monday...

I'll find out soon enough if GitHub Actions respects the yanking, but my Mac doesn't.
